import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import {
    DEFAULT_GIT_DIFF_FILE_LIMIT,
    DEFAULT_GIT_DIFF_SIZE_LIMIT,
    DEFAULT_GIT_LOG_LIMIT,
    DEFAULT_GIT_PATH,
    DEFAULT_GIT_TIMEOUT,
    MAX_GIT_DIFF_FILE_LIMIT,
    MAX_GIT_DIFF_SIZE_LIMIT,
    MAX_GIT_LOG_LIMIT,
    MAX_GIT_TIMEOUT,
    MIN_GIT_TIMEOUT,
} from './git.constants';

import type {
    GitBlameOptions,
    GitBranch,
    GitCommandOptions,
    GitCommandResult,
    GitCommit,
    GitCommitList,
    GitCommitQueryOptions,
    GitConfig,
    GitDiff,
    GitDiffFile,
    GitDiffOptions,
    GitRepository,
    GitStatus,
} from './git.types';

import {
    GitBlameResult,
    GitBlameLine,
} from './models/git-blame.model';

const execFileAsync = promisify(execFile);

/**
 * GitService
 *
 * Provides controlled execution of Git commands and
 * repository-level validation.
 *
 * All Git MCP tools should use this service rather than
 * executing Git commands directly.
 */
export class GitService {
    private readonly gitPath: string;

    private readonly defaultTimeout: number;

    /**
     * Creates a GitService instance.
     *
     * @param config Git service configuration.
     */
    constructor(config: GitConfig = {}) {
        this.gitPath = config.gitPath ?? DEFAULT_GIT_PATH;

        this.defaultTimeout = this.normalizeTimeout(
            config.timeout ?? DEFAULT_GIT_TIMEOUT,
        );
    }

    /**
     * Executes a Git command in a controlled manner.
     *
     * @param args Git command arguments.
     * @param options Command execution options.
     */
    async execute(
        args: string[],
        options: GitCommandOptions,
    ): Promise<GitCommandResult> {
        const timeout = this.normalizeTimeout(
            options.timeout ?? this.defaultTimeout,
        );

        const command = [...args];

        try {
            const result = await execFileAsync(
                this.gitPath,
                command,
                {
                    cwd: options.cwd,
                    timeout,
                    windowsHide: true,
                    maxBuffer: 10 * 1024 * 1024,
                },
            );

            return {
                success: true,
                command,
                stdout: this.normalizeOutput(result.stdout),
                stderr: this.normalizeOutput(result.stderr),
                exitCode: 0,
                timedOut: false,
            };
        } catch (error: unknown) {
            return this.createErrorResult(command, error);
        }
    }

    /**
 * Parses Git porcelain status output.
 *
 * Git porcelain v1 format:
 *
 * XY filename
 *
 * X = index/staged status
 * Y = working-tree status
 */
    private parseStatus(
        output: string,
        branch: string,
    ): Omit<GitStatus, 'ahead' | 'behind'> {
        const modified: string[] = [];
        const added: string[] = [];
        const deleted: string[] = [];
        const untracked: string[] = [];

        const lines = output
            .split(/\r?\n/)
            .filter((line) => line.length > 0);

        for (const line of lines) {
            if (line.length < 3) {
                continue;
            }

            const indexStatus = line[0];
            const workingTreeStatus = line[1];
            const filePath = line.slice(3);

            /*
             * Untracked
             *
             * ?? filename
             */
            if (
                indexStatus === '?' &&
                workingTreeStatus === '?'
            ) {
                untracked.push(filePath);
                continue;
            }

            /*
             * Added
             *
             * A file added to the index.
             */
            if (
                indexStatus === 'A' ||
                workingTreeStatus === 'A'
            ) {
                added.push(filePath);
                continue;
            }

            /*
             * Deleted
             */
            if (
                indexStatus === 'D' ||
                workingTreeStatus === 'D'
            ) {
                deleted.push(filePath);
                continue;
            }

            /*
             * Modified
             */
            if (
                indexStatus === 'M' ||
                workingTreeStatus === 'M'
            ) {
                modified.push(filePath);
            }
        }

        return {
            branch,
            modified,
            added,
            deleted,
            untracked,
        };
    }

    /**
 * Parses the structured output generated by git log.
 *
 * Record separator:
 *     %x1e
 *
 * Field separator:
 *     %x1f
 */
    private parseCommitLog(
        output: string,
    ): GitCommit[] {
        const commits: GitCommit[] = [];

        const records = output
            .split('\x1e')
            .map((record) => record.trim())
            .filter(Boolean);

        for (const record of records) {
            const fields = record.split('\x1f');

            if (fields.length < 5) {
                continue;
            }

            const [
                hash,
                author,
                email,
                date,
                message,
            ] = fields;

            commits.push({
                hash,
                author,
                email,
                date,
                message,
            });
        }

        return commits;
    }

    /**
 * Normalizes the requested Git log limit.
 */
    private normalizeLogLimit(
        limit?: number,
    ): number {
        if (
            limit === undefined ||
            !Number.isFinite(limit)
        ) {
            return DEFAULT_GIT_LOG_LIMIT;
        }

        return Math.min(
            Math.max(Math.floor(limit), 1),
            MAX_GIT_LOG_LIMIT,
        );
    }

    /**
 * Gets ahead/behind information relative to the upstream branch.
 */
    private async getAheadBehind(
        workspacePath: string,
    ): Promise<{
        ahead: number;
        behind: number;
    }> {
        const result = await this.execute(
            [
                'rev-list',
                '--left-right',
                '--count',
                'HEAD...@{upstream}',
            ],
            {
                cwd: workspacePath,
            },
        );

        /*
         * A repository may not have an upstream branch.
         *
         * In that case there is no meaningful ahead/behind
         * information, so return zero values.
         */
        if (!result.success) {
            return {
                ahead: 0,
                behind: 0,
            };
        }

        const values = result.stdout
            .trim()
            .split(/\s+/);

        if (values.length !== 2) {
            return {
                ahead: 0,
                behind: 0,
            };
        }

        const ahead = Number.parseInt(
            values[0],
            10,
        );

        const behind = Number.parseInt(
            values[1],
            10,
        );

        return {
            ahead: Number.isNaN(ahead) ? 0 : ahead,
            behind: Number.isNaN(behind) ? 0 : behind,
        };
    }

    /**
     * Checks whether the supplied workspace path
     * is inside a Git working tree.
     *
     * @param workspacePath Path to the workspace.
     * @returns true when the path belongs to a Git repository.
     */
    async isRepository(workspacePath: string): Promise<boolean> {
        const result = await this.execute(
            ['rev-parse', '--is-inside-work-tree'],
            {
                cwd: workspacePath,
            },
        );

        return (
            result.success &&
            result.stdout.trim() === 'true'
        );
    }



    /**
     * Validates a Git repository and returns basic repository information.
     *
     * @param workspacePath Path to the workspace.
    */
    async validateRepository(
        workspacePath: string,
    ): Promise<GitRepository> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            return {
                isRepository: false,
                root: '',
                currentBranch: '',
            };
        }

        const root = await this.getRepositoryRoot(
            workspacePath,
        );

        const currentBranch = await this.getCurrentBranch(
            workspacePath,
        );

        return {
            isRepository: true,
            root,
            currentBranch,
        };
    }

    /**
     * Gets the root directory of the Git repository.
     *
     * @param workspacePath Path inside the repository.
     * @returns Absolute repository root path.
     *
     * @throws Error when the workspace is not a Git repository.
     */
    async getRepositoryRoot(workspacePath: string): Promise<string> {
        const repositoryCheck = await this.isRepository(workspacePath);

        if (!repositoryCheck) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            ['rev-parse', '--show-toplevel'],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to determine Git repository root.',
            );
        }

        return result.stdout.trim();
    }

    /**
     * Normalizes Git command timeout values.
     */
    private normalizeTimeout(timeout: number): number {
        if (!Number.isFinite(timeout)) {
            return DEFAULT_GIT_TIMEOUT;
        }

        return Math.min(
            Math.max(timeout, MIN_GIT_TIMEOUT),
            MAX_GIT_TIMEOUT,
        );
    }

    /**
     * Normalizes child-process output.
     */
    private normalizeOutput(
        output: string | Buffer,
    ): string {
        return output.toString();
    }

    /**
     * Converts an unknown process error into a structured
     * GitCommandResult.
     */
    private createErrorResult(
        command: string[],
        error: unknown,
    ): GitCommandResult {
        const processError = error as {
            stdout?: string | Buffer;
            stderr?: string | Buffer;
            code?: number | string;
            killed?: boolean;
            signal?: string;
            message?: string;
        };

        const timedOut =
            processError.killed === true &&
            processError.signal === 'SIGTERM';

        const exitCode =
            typeof processError.code === 'number'
                ? processError.code
                : undefined;

        return {
            success: false,
            command,
            stdout: processError.stdout
                ? this.normalizeOutput(processError.stdout)
                : '',
            stderr: processError.stderr
                ? this.normalizeOutput(processError.stderr)
                : '',
            exitCode,
            timedOut,
            error: timedOut
                ? 'Git command timed out.'
                : processError.message ??
                'Git command execution failed.',
        };
    }

    /**
     * Creates a consistent repository validation error.
     */
    private createRepositoryError(
        result: GitCommandResult,
    ): string {
        if (result.timedOut) {
            return 'Git repository validation timed out.';
        }

        if (result.stderr.trim()) {
            return result.stderr.trim();
        }

        return result.error ?? 'Not a Git repository.';
    }

    /**
     * Gets the current Git branch.
     *
     * @param workspacePath Path inside the repository.
     * @returns Current branch name.
     */

    async getCurrentBranch(
        workspacePath: string,
    ): Promise<string> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            ['branch', '--show-current'],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to determine current Git branch.',
            );
        }

        return result.stdout.trim();
    }

    /**
 * Gets the current Git working-tree status.
 *
 * @param workspacePath Path inside the Git repository.
 * @returns Structured Git status.
 */
    async getStatus(
        workspacePath: string,
    ): Promise<GitStatus> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const branch = await this.getCurrentBranch(
            workspacePath,
        );

        const statusResult = await this.execute(
            [
                'status',
                '--porcelain=v1',
                '--untracked-files=all',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!statusResult.success) {
            throw new Error(
                statusResult.stderr.trim() ||
                statusResult.error ||
                'Unable to determine Git status.',
            );
        }

        const status = this.parseStatus(
            statusResult.stdout,
            branch,
        );

        const tracking = await this.getAheadBehind(
            workspacePath,
        );

        return {
            ...status,
            ahead: tracking.ahead,
            behind: tracking.behind,
        };
    }

    /**
    * Lists local Git branches.
    *
    * @param workspacePath Path inside the Git repository.
    * @returns Branch names.
    */
    async listBranches(
        workspacePath: string,
    ): Promise<string[]> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            [
                'branch',
                '--format=%(refname:short)',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to list Git branches.',
            );
        }

        return result.stdout
            .split(/\r?\n/)
            .map((branch) => branch.trim())
            .filter(Boolean);
    }

    /**
     * Gets information about a Git branch.
     *
     * @param workspacePath Path inside the repository.
     * @param branchName Branch name.
     */
    async getBranchInfo(
        workspacePath: string,
        branchName: string,
    ): Promise<GitBranch> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const branches = await this.listBranches(
            workspacePath,
        );

        if (!branches.includes(branchName)) {
            throw new Error(
                `Git branch not found: ${branchName}`,
            );
        }

        const currentBranch =
            await this.getCurrentBranch(
                workspacePath,
            );

        return {
            name: branchName,
            current: branchName === currentBranch,
            local: true,
        };
    }

    /**
 * Gets details for a specific Git commit.
 *
 * @param workspacePath Path inside the Git repository.
 * @param commitReference Commit hash or Git reference.
 */
    async getCommit(
        workspacePath: string,
        commitReference: string,
    ): Promise<GitCommit> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        if (!commitReference.trim()) {
            throw new Error(
                'Commit reference is required.',
            );
        }

        const result = await this.execute(
            [
                'show',
                '-s',
                '--date=iso-strict',
                '--format=%H%x1f%an%x1f%ae%x1f%aI%x1f%s',
                commitReference,
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                `Unable to retrieve commit: ${commitReference}`,
            );
        }

        const fields = result.stdout
            .trim()
            .split('\x1f');

        if (fields.length < 5) {
            throw new Error(
                `Unable to parse commit information: ${commitReference}`,
            );
        }

        const [
            hash,
            author,
            email,
            date,
            message,
        ] = fields;

        return {
            hash,
            author,
            email,
            date,
            message,
        };
    }

    /**
 * Searches Git commit history using supported filters.
 *
 * @param workspacePath Path inside the Git repository.
 * @param options Search options.
 */
    async searchCommits(
        workspacePath: string,
        options: GitCommitQueryOptions = {},
    ): Promise<GitCommitList> {
        return this.getLog(
            workspacePath,
            options,
        );
    }


    /**
     * Gets commit history for a Git repository.
     *
     * @param workspacePath Path inside the Git repository.
     * @param options Commit query options.
     */
    async getLog(
        workspacePath: string,
        options: GitCommitQueryOptions = {},
    ): Promise<GitCommitList> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const limit = this.normalizeLogLimit(
            options.limit,
        );

        const args: string[] = [
            'log',
            `-${limit + 1}`,
            '--date=iso-strict',
            '--format=%H%x1f%an%x1f%ae%x1f%aI%x1f%s%x1e',
        ];

        if (options.author) {
            args.push(`--author=${options.author}`);
        }

        if (options.since) {
            args.push(`--since=${options.since}`);
        }

        if (options.until) {
            args.push(`--until=${options.until}`);
        }

        if (options.branch) {
            args.push(options.branch);
        }

        const result = await this.execute(
            args,
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to retrieve Git commit history.',
            );
        }

        const parsedCommits =
            this.parseCommitLog(result.stdout);

        const hasMore =
            parsedCommits.length > limit;

        const commits = parsedCommits.slice(
            0,
            limit,
        );

        return {
            commits,
            count: commits.length,
            hasMore,
        };
    }

    async getDiff(
        workspacePath: string,
        options: GitDiffOptions = {},
    ): Promise<GitDiff> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const fileLimit =
            this.normalizeDiffFileLimit(options.fileLimit);

        const maxDiffSize =
            this.normalizeDiffSizeLimit(options.maxDiffSize);

        const result = await this.execute(
            [
                'diff',
                '--no-ext-diff',
                '--unified=3',
                '--no-color',
                '--',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to retrieve Git diff.',
            );
        }

        const output = result.stdout;

        const limitedOutput =
            output.length > maxDiffSize
                ? output.slice(0, maxDiffSize)
                : output;

        const truncated =
            output.length > maxDiffSize;

        const files =
            this.parseDiff(limitedOutput, fileLimit);

        return this.buildDiffResult(files, truncated);
    }

    async getCommitDiff(
        workspacePath: string,
        commitReference: string,
        options: GitDiffOptions = {},
    ): Promise<GitDiff> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        if (!commitReference.trim()) {
            throw new Error('Commit reference is required.');
        }

        const fileLimit =
            this.normalizeDiffFileLimit(options.fileLimit);

        const maxDiffSize =
            this.normalizeDiffSizeLimit(options.maxDiffSize);

        const result = await this.execute(
            [
                'show',
                '--format=',
                '--no-ext-diff',
                '--unified=3',
                '--no-color',
                commitReference,
                '--',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                `Unable to retrieve diff for commit: ${commitReference}`,
            );
        }

        const output = result.stdout;

        const limitedOutput =
            output.length > maxDiffSize
                ? output.slice(0, maxDiffSize)
                : output;

        const truncated =
            output.length > maxDiffSize;

        const files =
            this.parseDiff(limitedOutput, fileLimit);

        return this.buildDiffResult(files, truncated);
    }

    async getFileDiff(
        workspacePath: string,
        filePath: string,
        options: GitDiffOptions = {},
    ): Promise<GitDiff> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        if (!filePath.trim()) {
            throw new Error('File path is required.');
        }

        const fileLimit =
            this.normalizeDiffFileLimit(options.fileLimit);

        const maxDiffSize =
            this.normalizeDiffSizeLimit(options.maxDiffSize);

        const result = await this.execute(
            [
                'diff',
                '--no-ext-diff',
                '--unified=3',
                '--no-color',
                '--',
                filePath,
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                `Unable to retrieve diff for file: ${filePath}`,
            );
        }

        const output = result.stdout;

        const limitedOutput =
            output.length > maxDiffSize
                ? output.slice(0, maxDiffSize)
                : output;

        const truncated =
            output.length > maxDiffSize;

        const files =
            this.parseDiff(
                limitedOutput,
                Math.min(fileLimit, 1),
            );

        return this.buildDiffResult(files, truncated);
    }

    private parseDiff(
        output: string,
        fileLimit: number,
    ): GitDiffFile[] {
        if (!output.trim()) {
            return [];
        }

        const files: GitDiffFile[] = [];

        const sections =
            output.split(/^diff --git /m);

        for (const section of sections) {
            if (!section.trim()) {
                continue;
            }

            if (files.length >= fileLimit) {
                break;
            }

            const parsed =
                this.parseDiffSection(section);

            if (parsed) {
                files.push(parsed);
            }
        }

        return files;
    }

    private parseDiffSection(
        section: string,
    ): GitDiffFile | null {
        const lines =
            section.split(/\r?\n/);

        if (lines.length === 0) {
            return null;
        }

        const header = lines[0];

        const pathMatch =
            header.match(/^a\/(.+?) b\/(.+)$/);

        if (!pathMatch) {
            return null;
        }

        const oldPath = pathMatch[1];
        const newPath = pathMatch[2];

        let status: GitDiffFile['status'] = 'modified';

        if (section.includes('\nnew file mode ')) {
            status = 'added';
        } else if (section.includes('\ndeleted file mode ')) {
            status = 'deleted';
        } else if (section.includes('\nrename from ')) {
            status = 'renamed';
        } else if (section.includes('\ncopy from ')) {
            status = 'copied';
        }

        const additions =
            this.countDiffLines(lines, 'addition');

        const deletions =
            this.countDiffLines(lines, 'deletion');

        return {
            path:
                status === 'renamed'
                    ? `${oldPath} -> ${newPath}`
                    : newPath,
            status,
            additions,
            deletions,
            diff: `diff --git ${section}`,
        };
    }

    private countDiffLines(
        lines: string[],
        type: 'addition' | 'deletion',
    ): number {
        let count = 0;

        for (const line of lines) {
            if (
                line.startsWith('+++') ||
                line.startsWith('---')
            ) {
                continue;
            }

            if (
                type === 'addition' &&
                line.startsWith('+')
            ) {
                count++;
            }

            if (
                type === 'deletion' &&
                line.startsWith('-')
            ) {
                count++;
            }
        }

        return count;
    }

    private buildDiffResult(
        files: GitDiffFile[],
        truncated: boolean,
    ): GitDiff {
        const additions =
            files.reduce(
                (total, file) =>
                    total + file.additions,
                0,
            );

        const deletions =
            files.reduce(
                (total, file) =>
                    total + file.deletions,
                0,
            );

        return {
            files,
            fileCount: files.length,
            additions,
            deletions,
            truncated,
        };
    }

    private normalizeDiffFileLimit(
        limit?: number,
    ): number {
        if (
            limit === undefined ||
            !Number.isFinite(limit)
        ) {
            return DEFAULT_GIT_DIFF_FILE_LIMIT;
        }

        return Math.min(
            Math.max(
                Math.floor(limit),
                1,
            ),
            MAX_GIT_DIFF_FILE_LIMIT,
        );
    }

    private normalizeDiffSizeLimit(
        size?: number,
    ): number {
        if (
            size === undefined ||
            !Number.isFinite(size)
        ) {
            return DEFAULT_GIT_DIFF_SIZE_LIMIT;
        }

        return Math.min(
            Math.max(
                Math.floor(size),
                1,
            ),
            MAX_GIT_DIFF_SIZE_LIMIT,
        );
    }

    /**
 * Gets Git blame information for a file.
 *
 * This method is responsible only for:
 * - repository validation
 * - input validation
 * - Git command construction
 * - controlled Git command execution
 *
 * Parsing of the porcelain blame output is handled
 * separately in the Git blame parsing milestone.
 *
 * @param options Git blame options.
 * @returns Raw Git command result containing blame output.
 */
    /**
  * Gets Git blame information for a file.
  *
  * Performs:
  * - repository validation
  * - input validation
  * - line-range validation
  * - Git command construction
  * - controlled Git command execution
  * - porcelain output parsing
  *
  * @param options Git blame options.
  * @returns Structured Git blame information.
  */
    async blame(
        options: GitBlameOptions,
    ): Promise<GitBlameResult> {
        const {
            workspacePath,
            filePath,
            startLine,
            endLine,
            revision,
        } = options;

        if (!workspacePath.trim()) {
            throw new Error(
                'Workspace path is required.',
            );
        }

        if (!filePath.trim()) {
            throw new Error(
                'File path is required.',
            );
        }

        if (
            startLine !== undefined &&
            (
                !Number.isInteger(startLine) ||
                startLine < 1
            )
        ) {
            throw new Error(
                'Start line must be a positive integer.',
            );
        }

        if (
            endLine !== undefined &&
            (
                !Number.isInteger(endLine) ||
                endLine < 1
            )
        ) {
            throw new Error(
                'End line must be a positive integer.',
            );
        }

        if (
            startLine !== undefined &&
            endLine !== undefined &&
            endLine < startLine
        ) {
            throw new Error(
                'End line must be greater than or equal to start line.',
            );
        }

        if (
            revision !== undefined &&
            !revision.trim()
        ) {
            throw new Error(
                'Revision cannot be empty.',
            );
        }

        const isRepository =
            await this.isRepository(
                workspacePath,
            );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const args: string[] = [
            'blame',
            '--line-porcelain',
        ];

        /*
         * Optional line range.
         *
         * Both start and end:
         *   -L start,end
         *
         * Only start:
         *   -L start,start
         *
         * Only end:
         *   -L 1,end
         */
        if (
            startLine !== undefined &&
            endLine !== undefined
        ) {
            args.push(
                '-L',
                `${startLine},${endLine}`,
            );
        } else if (
            startLine !== undefined
        ) {
            args.push(
                '-L',
                `${startLine},${startLine}`,
            );
        } else if (
            endLine !== undefined
        ) {
            args.push(
                '-L',
                `1,${endLine}`,
            );
        }

        if (revision !== undefined) {
            args.push(revision);
        }

        args.push(
            '--',
            filePath,
        );

        const result = await this.execute(
            args,
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                `Unable to retrieve Git blame for file: ${filePath}`,
            );
        }

        const lines =
            this.parseBlame(
                result.stdout,
            );

        return {
            filePath,
            revision: revision ?? 'HEAD',
            startLine,
            endLine,
            lines,
            totalLines: lines.length,
        };
    }

    /**
 * Parses Git --line-porcelain blame output.
 *
 * @param output Raw Git blame porcelain output.
 * @returns Structured blame lines.
 */
    private parseBlame(
        output: string,
    ): GitBlameLine[] {
        if (!output.trim()) {
            return [];
        }

        const lines = output.split(/\r?\n/);
        const blameLines: GitBlameLine[] = [];

        let index = 0;

        while (index < lines.length) {
            const header = lines[index];

            if (!header.trim()) {
                index++;
                continue;
            }

            const headerMatch = header.match(
                /^([0-9a-f]+)\s+(\d+)\s+(\d+)(?:\s+(\d+))?$/,
            );

            if (!headerMatch) {
                index++;
                continue;
            }

            const commit = headerMatch[1];
            const finalLine = Number.parseInt(
                headerMatch[3],
                10,
            );

            let author = '';
            let authorEmail: string | undefined;
            let authorTime = '';
            let content = '';

            index++;

            while (index < lines.length) {
                const metadataLine = lines[index];

                /*
                 * Source line.
                 */
                if (metadataLine.startsWith('\t')) {
                    content = metadataLine.slice(1);
                    index++;
                    break;
                }

                /*
                 * Metadata.
                 */
                if (
                    metadataLine.startsWith('author ')
                ) {
                    author =
                        metadataLine.slice(
                            'author '.length,
                        );
                } else if (
                    metadataLine.startsWith(
                        'author-mail ',
                    )
                ) {
                    authorEmail =
                        metadataLine
                            .slice(
                                'author-mail '.length,
                            )
                            .trim();

                    if (
                        authorEmail.startsWith('<') &&
                        authorEmail.endsWith('>')
                    ) {
                        authorEmail =
                            authorEmail.slice(
                                1,
                                -1,
                            );
                    }
                } else if (
                    metadataLine.startsWith(
                        'author-time ',
                    )
                ) {
                    authorTime =
                        metadataLine.slice(
                            'author-time '.length,
                        );
                }

                index++;
            }

            blameLines.push({
                lineNumber: finalLine,
                commit,
                author,
                ...(authorEmail
                    ? { authorEmail }
                    : {}),
                date:
                    this.parseBlameTimestamp(
                        authorTime,
                    ),
                content,
            });
        }

        return blameLines;
    }

    /**
 * Converts a Git author timestamp into an ISO
 * timestamp.
 *
 * @param timestamp Git Unix timestamp.
 */
    private parseBlameTimestamp(
        timestamp: string,
    ): string {
        if (!timestamp.trim()) {
            return '';
        }

        const seconds =
            Number.parseInt(
                timestamp,
                10,
            );

        if (Number.isNaN(seconds)) {
            return '';
        }

        return new Date(
            seconds * 1000,
        ).toISOString();
    }

}