import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import {
    DEFAULT_GIT_LOG_LIMIT,
    DEFAULT_GIT_PATH,
    DEFAULT_GIT_TIMEOUT,
    MAX_GIT_LOG_LIMIT,
    MAX_GIT_TIMEOUT,
    MIN_GIT_TIMEOUT,
} from './git.constants';


import type {
    GitBranch,
    GitCommandOptions,
    GitCommandResult,
    GitCommit,
    GitCommitList,
    GitCommitQueryOptions,
    GitConfig,
    GitRepository,
    GitStatus,
} from './git.types';

const execFileAsync = promisify(execFile);

/**
 * GitService
 *
 * Provides controlled execution of Git commands and
 * repository-level validation.
 *
 * All Git MCP tools should use this service rather than
 * executing Git commands directly.
 */
export class GitService {
    private readonly gitPath: string;

    private readonly defaultTimeout: number;

    /**
     * Creates a GitService instance.
     *
     * @param config Git service configuration.
     */
    constructor(config: GitConfig = {}) {
        this.gitPath = config.gitPath ?? DEFAULT_GIT_PATH;

        this.defaultTimeout = this.normalizeTimeout(
            config.timeout ?? DEFAULT_GIT_TIMEOUT,
        );
    }

    /**
     * Executes a Git command in a controlled manner.
     *
     * @param args Git command arguments.
     * @param options Command execution options.
     */
    async execute(
        args: string[],
        options: GitCommandOptions,
    ): Promise<GitCommandResult> {
        const timeout = this.normalizeTimeout(
            options.timeout ?? this.defaultTimeout,
        );

        const command = [...args];

        try {
            const result = await execFileAsync(
                this.gitPath,
                command,
                {
                    cwd: options.cwd,
                    timeout,
                    windowsHide: true,
                    maxBuffer: 10 * 1024 * 1024,
                },
            );

            return {
                success: true,
                command,
                stdout: this.normalizeOutput(result.stdout),
                stderr: this.normalizeOutput(result.stderr),
                exitCode: 0,
                timedOut: false,
            };
        } catch (error: unknown) {
            return this.createErrorResult(command, error);
        }
    }

    /**
 * Parses Git porcelain status output.
 *
 * Git porcelain v1 format:
 *
 * XY filename
 *
 * X = index/staged status
 * Y = working-tree status
 */
    private parseStatus(
        output: string,
        branch: string,
    ): Omit<GitStatus, 'ahead' | 'behind'> {
        const modified: string[] = [];
        const added: string[] = [];
        const deleted: string[] = [];
        const untracked: string[] = [];

        const lines = output
            .split(/\r?\n/)
            .filter((line) => line.length > 0);

        for (const line of lines) {
            if (line.length < 3) {
                continue;
            }

            const indexStatus = line[0];
            const workingTreeStatus = line[1];
            const filePath = line.slice(3);

            /*
             * Untracked
             *
             * ?? filename
             */
            if (
                indexStatus === '?' &&
                workingTreeStatus === '?'
            ) {
                untracked.push(filePath);
                continue;
            }

            /*
             * Added
             *
             * A file added to the index.
             */
            if (
                indexStatus === 'A' ||
                workingTreeStatus === 'A'
            ) {
                added.push(filePath);
                continue;
            }

            /*
             * Deleted
             */
            if (
                indexStatus === 'D' ||
                workingTreeStatus === 'D'
            ) {
                deleted.push(filePath);
                continue;
            }

            /*
             * Modified
             */
            if (
                indexStatus === 'M' ||
                workingTreeStatus === 'M'
            ) {
                modified.push(filePath);
            }
        }

        return {
            branch,
            modified,
            added,
            deleted,
            untracked,
        };
    }

    /**
 * Parses the structured output generated by git log.
 *
 * Record separator:
 *     %x1e
 *
 * Field separator:
 *     %x1f
 */
    private parseCommitLog(
        output: string,
    ): GitCommit[] {
        const commits: GitCommit[] = [];

        const records = output
            .split('\x1e')
            .map((record) => record.trim())
            .filter(Boolean);

        for (const record of records) {
            const fields = record.split('\x1f');

            if (fields.length < 5) {
                continue;
            }

            const [
                hash,
                author,
                email,
                date,
                message,
            ] = fields;

            commits.push({
                hash,
                author,
                email,
                date,
                message,
            });
        }

        return commits;
    }

    /**
 * Normalizes the requested Git log limit.
 */
    private normalizeLogLimit(
        limit?: number,
    ): number {
        if (
            limit === undefined ||
            !Number.isFinite(limit)
        ) {
            return DEFAULT_GIT_LOG_LIMIT;
        }

        return Math.min(
            Math.max(Math.floor(limit), 1),
            MAX_GIT_LOG_LIMIT,
        );
    }

    /**
 * Gets ahead/behind information relative to the upstream branch.
 */
    private async getAheadBehind(
        workspacePath: string,
    ): Promise<{
        ahead: number;
        behind: number;
    }> {
        const result = await this.execute(
            [
                'rev-list',
                '--left-right',
                '--count',
                'HEAD...@{upstream}',
            ],
            {
                cwd: workspacePath,
            },
        );

        /*
         * A repository may not have an upstream branch.
         *
         * In that case there is no meaningful ahead/behind
         * information, so return zero values.
         */
        if (!result.success) {
            return {
                ahead: 0,
                behind: 0,
            };
        }

        const values = result.stdout
            .trim()
            .split(/\s+/);

        if (values.length !== 2) {
            return {
                ahead: 0,
                behind: 0,
            };
        }

        const ahead = Number.parseInt(
            values[0],
            10,
        );

        const behind = Number.parseInt(
            values[1],
            10,
        );

        return {
            ahead: Number.isNaN(ahead) ? 0 : ahead,
            behind: Number.isNaN(behind) ? 0 : behind,
        };
    }

    /**
     * Checks whether the supplied workspace path
     * is inside a Git working tree.
     *
     * @param workspacePath Path to the workspace.
     * @returns true when the path belongs to a Git repository.
     */
    async isRepository(workspacePath: string): Promise<boolean> {
        const result = await this.execute(
            ['rev-parse', '--is-inside-work-tree'],
            {
                cwd: workspacePath,
            },
        );

        return (
            result.success &&
            result.stdout.trim() === 'true'
        );
    }



    /**
     * Validates a Git repository and returns basic repository information.
     *
     * @param workspacePath Path to the workspace.
    */
    async validateRepository(
        workspacePath: string,
    ): Promise<GitRepository> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            return {
                isRepository: false,
                root: '',
                currentBranch: '',
            };
        }

        const root = await this.getRepositoryRoot(
            workspacePath,
        );

        const currentBranch = await this.getCurrentBranch(
            workspacePath,
        );

        return {
            isRepository: true,
            root,
            currentBranch,
        };
    }

    /**
     * Gets the root directory of the Git repository.
     *
     * @param workspacePath Path inside the repository.
     * @returns Absolute repository root path.
     *
     * @throws Error when the workspace is not a Git repository.
     */
    async getRepositoryRoot(workspacePath: string): Promise<string> {
        const repositoryCheck = await this.isRepository(workspacePath);

        if (!repositoryCheck) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            ['rev-parse', '--show-toplevel'],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to determine Git repository root.',
            );
        }

        return result.stdout.trim();
    }

    /**
     * Normalizes Git command timeout values.
     */
    private normalizeTimeout(timeout: number): number {
        if (!Number.isFinite(timeout)) {
            return DEFAULT_GIT_TIMEOUT;
        }

        return Math.min(
            Math.max(timeout, MIN_GIT_TIMEOUT),
            MAX_GIT_TIMEOUT,
        );
    }

    /**
     * Normalizes child-process output.
     */
    private normalizeOutput(
        output: string | Buffer,
    ): string {
        return output.toString();
    }

    /**
     * Converts an unknown process error into a structured
     * GitCommandResult.
     */
    private createErrorResult(
        command: string[],
        error: unknown,
    ): GitCommandResult {
        const processError = error as {
            stdout?: string | Buffer;
            stderr?: string | Buffer;
            code?: number | string;
            killed?: boolean;
            signal?: string;
            message?: string;
        };

        const timedOut =
            processError.killed === true &&
            processError.signal === 'SIGTERM';

        const exitCode =
            typeof processError.code === 'number'
                ? processError.code
                : undefined;

        return {
            success: false,
            command,
            stdout: processError.stdout
                ? this.normalizeOutput(processError.stdout)
                : '',
            stderr: processError.stderr
                ? this.normalizeOutput(processError.stderr)
                : '',
            exitCode,
            timedOut,
            error: timedOut
                ? 'Git command timed out.'
                : processError.message ??
                'Git command execution failed.',
        };
    }

    /**
     * Creates a consistent repository validation error.
     */
    private createRepositoryError(
        result: GitCommandResult,
    ): string {
        if (result.timedOut) {
            return 'Git repository validation timed out.';
        }

        if (result.stderr.trim()) {
            return result.stderr.trim();
        }

        return result.error ?? 'Not a Git repository.';
    }

    /**
     * Gets the current Git branch.
     *
     * @param workspacePath Path inside the repository.
     * @returns Current branch name.
     */

    async getCurrentBranch(
        workspacePath: string,
    ): Promise<string> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            ['branch', '--show-current'],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to determine current Git branch.',
            );
        }

        return result.stdout.trim();
    }

    /**
 * Gets the current Git working-tree status.
 *
 * @param workspacePath Path inside the Git repository.
 * @returns Structured Git status.
 */
    async getStatus(
        workspacePath: string,
    ): Promise<GitStatus> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const branch = await this.getCurrentBranch(
            workspacePath,
        );

        const statusResult = await this.execute(
            [
                'status',
                '--porcelain=v1',
                '--untracked-files=all',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!statusResult.success) {
            throw new Error(
                statusResult.stderr.trim() ||
                statusResult.error ||
                'Unable to determine Git status.',
            );
        }

        const status = this.parseStatus(
            statusResult.stdout,
            branch,
        );

        const tracking = await this.getAheadBehind(
            workspacePath,
        );

        return {
            ...status,
            ahead: tracking.ahead,
            behind: tracking.behind,
        };
    }

    /**
    * Lists local Git branches.
    *
    * @param workspacePath Path inside the Git repository.
    * @returns Branch names.
    */
    async listBranches(
        workspacePath: string,
    ): Promise<string[]> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const result = await this.execute(
            [
                'branch',
                '--format=%(refname:short)',
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to list Git branches.',
            );
        }

        return result.stdout
            .split(/\r?\n/)
            .map((branch) => branch.trim())
            .filter(Boolean);
    }

    /**
     * Gets information about a Git branch.
     *
     * @param workspacePath Path inside the repository.
     * @param branchName Branch name.
     */
    async getBranchInfo(
        workspacePath: string,
        branchName: string,
    ): Promise<GitBranch> {
        const isRepository = await this.isRepository(
            workspacePath,
        );

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const branches = await this.listBranches(
            workspacePath,
        );

        if (!branches.includes(branchName)) {
            throw new Error(
                `Git branch not found: ${branchName}`,
            );
        }

        const currentBranch =
            await this.getCurrentBranch(
                workspacePath,
            );

        return {
            name: branchName,
            current: branchName === currentBranch,
            local: true,
        };
    }

    /**
 * Gets details for a specific Git commit.
 *
 * @param workspacePath Path inside the Git repository.
 * @param commitReference Commit hash or Git reference.
 */
    async getCommit(
        workspacePath: string,
        commitReference: string,
    ): Promise<GitCommit> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        if (!commitReference.trim()) {
            throw new Error(
                'Commit reference is required.',
            );
        }

        const result = await this.execute(
            [
                'show',
                '-s',
                '--date=iso-strict',
                '--format=%H%x1f%an%x1f%ae%x1f%aI%x1f%s',
                commitReference,
            ],
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                `Unable to retrieve commit: ${commitReference}`,
            );
        }

        const fields = result.stdout
            .trim()
            .split('\x1f');

        if (fields.length < 5) {
            throw new Error(
                `Unable to parse commit information: ${commitReference}`,
            );
        }

        const [
            hash,
            author,
            email,
            date,
            message,
        ] = fields;

        return {
            hash,
            author,
            email,
            date,
            message,
        };
    }

    /**
 * Searches Git commit history using supported filters.
 *
 * @param workspacePath Path inside the Git repository.
 * @param options Search options.
 */
    async searchCommits(
        workspacePath: string,
        options: GitCommitQueryOptions = {},
    ): Promise<GitCommitList> {
        return this.getLog(
            workspacePath,
            options,
        );
    }


    /**
     * Gets commit history for a Git repository.
     *
     * @param workspacePath Path inside the Git repository.
     * @param options Commit query options.
     */
    async getLog(
        workspacePath: string,
        options: GitCommitQueryOptions = {},
    ): Promise<GitCommitList> {
        const isRepository =
            await this.isRepository(workspacePath);

        if (!isRepository) {
            throw new Error(
                `The workspace is not a Git repository: ${workspacePath}`,
            );
        }

        const limit = this.normalizeLogLimit(
            options.limit,
        );

        const args: string[] = [
            'log',
            `-${limit + 1}`,
            '--date=iso-strict',
            '--format=%H%x1f%an%x1f%ae%x1f%aI%x1f%s%x1e',
        ];

        if (options.author) {
            args.push(`--author=${options.author}`);
        }

        if (options.since) {
            args.push(`--since=${options.since}`);
        }

        if (options.until) {
            args.push(`--until=${options.until}`);
        }

        if (options.branch) {
            args.push(options.branch);
        }

        const result = await this.execute(
            args,
            {
                cwd: workspacePath,
            },
        );

        if (!result.success) {
            throw new Error(
                result.stderr.trim() ||
                result.error ||
                'Unable to retrieve Git commit history.',
            );
        }

        const parsedCommits =
            this.parseCommitLog(result.stdout);

        const hasMore =
            parsedCommits.length > limit;

        const commits = parsedCommits.slice(
            0,
            limit,
        );

        return {
            commits,
            count: commits.length,
            hasMore,
        };
    }

}