export * from "./directory.detector";
export * from "./file.detector";
export * from "./module.detector";
export * from "./controller.detector";
export * from "./service.detector";
export * from "./route.detector";
export * from "./model.detector";
export * from "./entryPoint.detector";
export * from "./architecture.detector"