export const MEMORY_CONFIG = {

    MAX_MESSAGES: 20,

    SESSION_TIMEOUT_MINUTES: 60,

    CLEANUP_INTERVAL_MINUTES: 30,

    SUMMARY_THRESHOLD: 40,

    MAX_CONTEXT_MESSAGES: 10,

    ENABLE_SUMMARIZATION: true

};